### ISSUE TITLE
Dragonfly distribution changes

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#247]
CC @LexiconCode

Christo Butcher (@t4ngo) has kindly allowed us the use of the original ['dragonfly' PyPI](https://pypi.org/project/dragonfly/) channel for distribution and has archived the original [t4ngo/dragonfly](https://github.com/t4ngo/dragonfly) repository. I'd like to start releasing new versions via the original channel instead of via [dragonfly2](https://pypi.org/project/dragonfly2/).

@calmofthestorm Christo has given you and myself owner-level access to the dragonfly channel. You also have this access to the dragonfly2 channel. This way, we can add new maintainers / owners in the future as necessary.

We can stick with the same version numbers used for dragonfly2. I'm uncertain whether releases for dragonfly2 should continue after this. Maybe we could stop them at version 1.0.0?

### TODO
- [ ] Reupload all previous release versions to the dragonfly PyPI channel.
- [ ] Make appropriate changes to Dragonfly's source code + documentation
- [ ] Distribute the next version there.
- [ ] After the next release, make announcements about this change:
  - [ ] [Dragonfly mailing list](https://groups.google.com/forum/#!topic/dragonflyspeech)
  - [ ] [Dragonfly Gitter channel](https://gitter.im/dictation-toolbox/dragonfly).
